In [95]:
import pandas as pd
import numpy as np
import wget

# Q-1

In [27]:
pd.__version__

'1.4.4'

In [28]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

In [29]:
df= pd.read_csv(url)

# Q-2

In [30]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [32]:
num_cols = df.shape[1]
print("Number of columns in the dataset: ", num_cols)

Number of columns in the dataset:  10


# Q-3

In [33]:
missing_columns = df.isnull().sum()
missing_columns

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Q-4

In [36]:
unique_cols_ocean = df.ocean_proximity.unique()
unique_cols_ocean

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [41]:
unique_values = df['ocean_proximity'].nunique()
print(f'Number of uniqe values ocean_proximity column: {unique_values}')
print(f'These are : {unique_cols_ocean}')

Number of uniqe values ocean_proximity column: 5
These are : ['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


# Q-5

In [48]:
df_mean_house_value = df['median_house_value'].agg('mean')
df_mean_house_value

206855.81690891474

In [68]:
near_bay_house_avg_value = df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].agg('mean')
integer_average_value = round(near_bay_house_avg_value, 0)
integer_average_value

259212.0

In [69]:
print(f'Near bay housing average value is {integer_average_value} ')

Near bay housing average value is 259212.0 


# Q-6

In [90]:
average_of_total_bedrooms = df['total_bedrooms'].agg('mean')
average_of_total_bedrooms =round(average_of_total_bedrooms, 3)
average_of_total_bedrooms

537.871

In [91]:
df['total_bedrooms '] = df['total_bedrooms'].fillna(average_of_total_bedrooms)
df['total_bedrooms ']

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms , Length: 20640, dtype: float64

In [92]:
upg_average_of_total_bedrooms = df['total_bedrooms'].agg('mean')
upg_average_of_total_bedrooms = round(upg_average_of_total_bedrooms,3)
upg_average_of_total_bedrooms

537.871

In [93]:
print(f'First value of total_bedroom average: {average_of_total_bedrooms}')
print(f'New value of total_bedroom average: {upg_average_of_total_bedrooms}')

First value of total_bedroom average: 537.871
New value of total_bedroom average: 537.871


# Q-7

In [119]:
df= pd.read_csv(url)

In [225]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [120]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [230]:
island_df = df[df['ocean_proximity'] == 'ISLAND']
island_df = island_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [231]:
X = island_df.to_numpy()

In [232]:
X_transposed = X.T

In [233]:
XTX =np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [234]:
inverse_XTX = np.linalg.inv(XTX)

In [235]:
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [236]:
y = np.array([950, 1300, 800, 1000, 1300])

In [237]:
w = (inverse_XTX @ X_transposed) @ y

In [238]:
w

array([23.12330961, -1.48124183,  5.69922946])